### GET request to example server
POST http://localhost:8080/api/customer
Accept: application/json

{
  "nationality_id": 1,
  "name": "Bang Fadel",
  "dob": "1995-07-12",
  "phone_number": "0812345689434",
  "email": "fadel@example.com"
}

###

### GET request to example server
GET http://localhost:8080/api/health
###
### GET request to example server
GET http://localhost:8080/api/customer/1
Accept: application/json

###

### GET request to example server
GET http://localhost:8080/api/customer/1/family
###
POST http://localhost:8080/api/customer/1/family
Accept: application/json

{
  "relation": "adek",
  "name": "Udinssdsada",
  "dob": "1995-08-12"
}

###